#!/bin/bash
sleep 2

echo Hello Grace

sleep 2

echo Hello Steve

sleep 2

echo How are you dear?

sleep 3

echo Well Am good darling, How are you doing

sleep 4

echo Am kinda fine only to miss you

sleep 4

echo Woow!! I miss you more sweetheart

sleep 3

echo Come on and give me a hug boo..

sleep 3


echo mmmmh here darl....

sleep 3
